#add the files to index
C:\Users\thiag\Documents\arquivos_tratados\FSP.940101.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940102.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940103.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940104.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940105.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940106.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940107.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940108.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940109.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940110.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940111.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940112.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940113.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940114.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940115.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940116.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940117.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940118.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940119.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940120.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940121.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940122.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940123.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940124.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940125.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940126.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940127.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940128.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940129.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940130.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940131.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940201.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940202.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940203.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940204.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940205.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940206.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940207.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940208.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940209.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940210.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940211.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940212.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940213.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940214.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940215.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940216.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940217.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940218.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940219.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940220.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940221.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940222.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940223.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940224.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940225.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940226.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940227.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940228.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940301.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940302.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940303.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940304.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940305.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940306.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940307.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940308.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940309.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940310.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940311.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940312.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940313.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940314.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940315.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940316.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940317.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940318.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940319.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940320.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940321.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940322.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940323.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940324.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940325.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940326.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940327.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940328.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940329.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940330.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940331.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940401.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940402.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940403.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940404.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940405.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940406.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940407.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940408.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940409.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940410.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940411.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940412.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940413.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940414.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940415.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940416.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940417.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940418.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940419.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940420.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940421.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940422.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940423.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940424.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940425.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940426.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940427.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940428.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940429.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940430.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940501.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940502.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940503.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940504.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940505.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940506.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940507.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940508.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940509.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940510.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940511.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940512.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940513.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940514.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940515.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940516.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940517.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940518.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940519.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940520.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940521.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940522.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940523.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940524.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940525.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940526.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940527.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940528.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940529.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940530.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940531.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940601.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940602.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940603.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940604.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940605.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940606.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940607.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940608.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940609.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940610.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940611.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940612.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940613.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940614.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940615.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940616.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940617.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940618.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940619.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940620.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940621.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940622.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940623.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940624.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940625.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940626.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940627.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940628.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940629.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940630.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940701.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940702.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940703.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940704.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940705.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940706.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940707.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940708.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940709.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940710.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940711.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940712.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940713.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940714.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940715.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940716.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940717.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940718.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940719.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940720.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940721.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940722.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940723.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940724.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940725.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940726.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940727.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940728.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940729.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940730.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940731.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940801.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940802.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940803.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940804.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940805.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940806.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940807.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940808.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940809.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940810.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940811.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940812.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940813.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940814.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940815.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940816.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940817.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940818.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940819.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940820.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940821.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940822.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940823.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940824.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940825.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940826.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940827.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940828.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940829.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940830.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940831.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940901.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940902.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940903.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940904.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940905.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940906.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940907.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940908.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940909.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940910.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940911.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940912.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940913.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940914.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940915.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940916.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940917.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940918.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940919.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940920.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940921.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940922.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940923.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940924.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940925.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940926.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940927.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940928.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940929.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.940930.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941001.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941002.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941003.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941004.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941005.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941006.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941007.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941008.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941009.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941010.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941011.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941012.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941013.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941014.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941015.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941016.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941017.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941018.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941019.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941020.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941021.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941022.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941023.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941024.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941025.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941026.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941027.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941028.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941029.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941030.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941031.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941101.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941102.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941103.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941104.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941105.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941106.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941107.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941108.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941109.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941110.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941111.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941112.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941113.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941114.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941115.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941116.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941117.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941118.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941119.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941120.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941121.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941122.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941123.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941124.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941125.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941126.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941127.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941128.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941129.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941130.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941201.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941202.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941203.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941204.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941205.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941206.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941207.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941208.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941209.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941210.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941211.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941212.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941213.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941214.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941215.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941216.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941217.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941218.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941219.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941220.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941221.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941222.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941223.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941224.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941225.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941226.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941227.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941228.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941229.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941230.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.941231.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950101.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950102.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950103.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950104.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950105.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950106.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950107.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950108.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950109.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950110.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950111.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950112.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950113.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950114.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950115.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950116.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950117.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950118.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950119.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950120.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950121.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950122.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950123.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950124.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950125.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950126.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950127.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950128.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950129.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950130.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950131.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950201.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950202.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950203.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950204.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950205.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950206.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950207.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950208.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950209.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950210.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950211.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950212.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950213.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950214.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950215.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950216.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950217.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950218.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950219.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950220.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950221.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950222.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950223.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950224.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950225.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950226.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950227.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950228.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950301.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950302.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950303.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950304.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950305.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950306.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950307.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950308.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950309.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950310.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950311.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950312.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950313.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950314.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950315.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950316.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950317.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950318.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950319.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950320.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950321.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950322.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950323.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950324.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950325.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950326.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950327.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950328.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950329.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950330.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950331.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950401.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950402.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950403.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950404.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950405.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950406.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950407.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950408.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950409.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950410.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950411.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950412.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950413.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950414.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950415.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950416.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950417.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950418.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950419.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950420.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950421.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950422.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950423.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950424.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950425.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950426.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950427.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950428.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950429.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950430.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950501.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950502.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950503.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950504.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950505.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950506.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950507.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950508.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950509.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950510.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950511.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950512.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950513.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950514.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950515.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950516.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950517.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950518.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950519.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950520.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950521.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950522.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950523.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950524.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950525.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950526.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950527.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950528.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950529.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950530.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950531.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950601.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950602.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950603.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950604.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950605.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950606.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950607.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950608.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950609.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950610.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950611.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950612.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950613.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950614.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950615.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950616.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950617.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950618.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950619.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950620.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950621.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950622.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950623.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950624.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950625.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950626.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950627.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950628.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950629.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950630.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950701.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950702.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950703.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950704.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950705.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950706.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950707.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950708.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950709.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950710.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950711.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950712.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950713.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950714.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950715.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950716.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950717.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950718.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950719.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950720.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950721.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950722.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950723.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950724.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950725.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950726.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950727.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950728.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950729.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950730.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950731.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950801.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950802.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950803.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950804.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950805.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950806.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950807.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950808.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950809.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950810.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950811.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950812.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950813.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950814.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950815.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950816.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950817.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950818.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950819.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950820.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950821.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950822.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950823.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950824.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950825.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950826.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950827.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950828.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950829.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950830.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950831.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950901.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950902.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950903.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950904.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950905.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950906.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950907.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950908.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950909.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950910.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950911.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950912.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950913.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950914.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950915.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950916.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950917.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950918.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950919.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950920.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950921.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950922.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950923.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950924.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950925.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950926.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950927.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950928.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950929.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.950930.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951001.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951002.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951003.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951004.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951005.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951006.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951007.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951008.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951009.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951010.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951011.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951012.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951013.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951014.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951015.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951016.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951017.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951018.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951019.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951020.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951021.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951022.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951023.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951024.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951025.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951026.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951027.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951028.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951029.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951030.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951031.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951101.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951102.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951103.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951104.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951105.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951106.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951107.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951108.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951109.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951110.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951111.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951112.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951113.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951114.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951115.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951116.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951117.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951118.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951119.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951120.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951121.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951122.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951123.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951124.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951125.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951126.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951127.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951128.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951129.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951130.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951201.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951202.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951203.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951204.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951205.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951206.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951207.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951208.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951209.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951210.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951211.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951212.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951213.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951214.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951215.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951216.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951217.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951218.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951219.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951220.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951221.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951222.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951223.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951224.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951225.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951226.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951227.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951228.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951229.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951230.sgml
C:\Users\thiag\Documents\arquivos_tratados\FSP.951231.sgml
